env = SConscript('godot-cpp/SConstruct')
env.Append(CPPPATH='src/')
env.Append(CXXFLAGS=['-std=c++20'])

libpath = '../godot/core/lib/gdext' + env['SHLIBSUFFIX']
src = Glob('src/*.cpp')

if env['platform'] == 'windows':
    pass
elif env['platform'] == 'linux':
    sharedlib = env.SharedLibrary(libpath, src)
    Default(sharedlib)
