env = SConscript('godot-cpp/SConstruct')

env.Tool("compilation_db")
cdb = env.CompilationDatabase()

env.Append(CPPPATH='src/')

# Really need 20?
if env.get("is_msvc", False):
    env.Append(CXXFLAGS=["/std:c++20"])
else:
    env.Append(CXXFLAGS=["-std=c++20"])

outputpath = '../godot/core/lib/gdext' + env['SHLIBSUFFIX']
src = Glob('src/*.cpp')
sharedlib = env.SharedLibrary(outputpath, src)

Default([sharedlib, cdb])
# Default(sharedlib)

# if env['platform'] == 'windows':
#     sharedlib = env.SharedLibrary(outputpath, src)
# elif env['platform'] == 'linux':
#     sharedlib = env.SharedLibrary(outputpath, src)
#     Default(sharedlib)
