name: 🔗 GHA
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-runner
  cancel-in-progress: true

jobs:
  # android-build:
  #   name: 🤖 Android
  #   uses: ./.github/workflows/android_builds.yml
  # ios-build:
  #   name: 🍏 iOS
  #   uses: ./.github/workflows/ios_builds.yml
  linux-build:
    name: 🐧 Linux
    uses: ./.github/workflows/linux_builds.yml
  # macos-build:
  #   name: 🍎 macOS
  #   uses: ./.github/workflows/macos_builds.yml
  windows-build:
    name: 🏁 Windows
    uses: ./.github/workflows/windows_builds.yml
  # web-build:
  #   name: 🌐 Web
  #   uses: ./.github/workflows/web_builds.yml
